title: gChambers
author:
  name: Gregory Chambers
  email: 'greg@gChambers.com'
blog:
  route: ''
metadata:
    description: 'Sandbox site dedicated to understanding of and practicing with GRAVcms'
taxonomies: [category,tag,month]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1

# ++++++++++++++++++++
# COPYRIGHT
# module inspired by sora-article-blog-template
# called in the footer area of /user/themes/gregTheme/templates/partials/base.html.twig
# ++++++++++++++++++++
copyright:
    text1: Copyright
    # year: 2015
    url: http://s1nga.com
    text2: gregCompanyName

copyright2:
    text1: "additional Attribution"
    url: http://getgrav.org/
    text2: Grav Team
# ++++++++++++++++++++!
