title: gChambers
author:
  name: Gregory Chambers
  email: 'greg@gChambers.com'
blog:
  route: ''
metadata:
    description: 'Sandbox site dedicated to understanding of and practicing with GRAVcms'
taxonomies: [category,tag,month]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1
