cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
assets:
  css_pipeline: false
  css_minify: false
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_minify: false
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: true
  log: true
debugger:
  enabled: true
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: true
  cache_perms: '0755'
  debug: true
media:
  enable_media_timestamp: true
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: grav-site
  secure: false
  httponly: true
markdown:
  extra: true
